# Continuous Integration for vscode-css-languageservice
# Runs the TypeScript build & test suite on Node.js LTS versions

language: node_js

# Test against active LTS releases (adjust as project evolves)
node_js:
  - "20"
  - "18"

# Speed up by re‑using npm cache across builds
cache:
  npm: true
  directories:
    - ~/.npm

install:
  # Guaranteed clean, reproducible install
  - npm ci

script:
  # Compile the TypeScript (equivalent to `gulp compile` in the repo scripts)
  - npm run compile
  # Run the unit test suite (e.g. Jest / Mocha configured in package.json)
  - npm test

# Only build push & PR branches; ignore tags unless they come from the repo owner
branches:
  only:
    - /.*/
